/**
 * ============================================================================
 * Algorithm Library - Replay Player Engine (player.js)
 * ============================================================================
 * Universal timeline player that replays pre-recorded algorithm steps.
 * Decouples algorithm logic from presentation, providing:
 *   - Instant time-travel (step forward, step back, timeline scrubbing)
 *   - Dynamic playback speed control
 *   - Synchronized audio tone triggers
 *   - Accessible live-region and UI state events
 */

class AlgorithmPlayer {
    constructor(options = {}) {
        this.steps = [];
        this.currentStepIndex = -1;
        this.isPlaying = false;
        this.timer = null;
        this.speed = options.speed || 50; // ms per step
        this.enableSound = options.enableSound !== false; // can be disabled for silent/hero players
        this.onStep = options.onStep || (() => {});
        this.onStateChange = options.onStateChange || (() => {});
        this.onComplete = options.onComplete || (() => {});
        this.lastFrameTime = 0;
        this.rafId = null;
    }

    /**
     * Loads a new recorded sequence of steps into the player.
     * @param {Array} steps - Generated by an algorithm recorder
     * @param {boolean} autoPlay - Whether to immediately start playback
     */
    loadSteps(steps, autoPlay = false) {
        this.pause();
        this.steps = steps || [];
        this.currentStepIndex = -1;

        if (this.steps.length > 0) {
            this.currentStepIndex = 0;
            this.notifyStep(false);
        }

        if (autoPlay && this.steps.length > 1) {
            this.play();
        }
    }

    getCurrentStep() {
        if (this.currentStepIndex >= 0 && this.currentStepIndex < this.steps.length) {
            return this.steps[this.currentStepIndex];
        }
        return null;
    }

    getTotalSteps() {
        return this.steps.length;
    }

    /**
     * Updates playback speed (ms per step).
     * @param {number} ms - Milliseconds delay between steps
     */
    setSpeed(ms) {
        this.speed = Math.max(5, ms);
    }

    play() {
        if (this.isPlaying) return;
        if (this.steps.length === 0) return;

        // If at the end, restart from step 0
        if (this.currentStepIndex >= this.steps.length - 1) {
            this.currentStepIndex = 0;
            this.notifyStep(false);
        }

        this.isPlaying = true;
        this.onStateChange(true);
        this.lastFrameTime = performance.now();
        this.tick();
    }

    pause() {
        if (!this.isPlaying) return;
        this.isPlaying = false;
        if (this.rafId) {
            cancelAnimationFrame(this.rafId);
            this.rafId = null;
        }
        this.onStateChange(false);
    }

    togglePlayPause() {
        if (this.isPlaying) {
            this.pause();
        } else {
            this.play();
        }
    }

    tick() {
        if (!this.isPlaying) return;

        const loop = (timestamp) => {
            if (!this.isPlaying) return;

            const elapsed = timestamp - this.lastFrameTime;
            if (elapsed >= this.speed) {
                this.lastFrameTime = timestamp - (elapsed % this.speed);
                const hasMore = this.nextStep(true);
                if (!hasMore) {
                    this.pause();
                    this.onComplete();
                    return;
                }
            }
            this.rafId = requestAnimationFrame(loop);
        };

        this.rafId = requestAnimationFrame(loop);
    }

    /**
     * Advances to next step in timeline.
     * @param {boolean} playSound - Whether to trigger audio synthesizer
     * @returns {boolean} True if more steps remain
     */
    nextStep(playSound = true) {
        if (this.currentStepIndex < this.steps.length - 1) {
            this.currentStepIndex++;
            this.notifyStep(playSound);
            return true;
        }
        return false;
    }

    /**
     * Steps backward to previous step in timeline.
     */
    prevStep() {
        this.pause();
        if (this.currentStepIndex > 0) {
            this.currentStepIndex--;
            this.notifyStep(false);
            return true;
        }
        return false;
    }

    /**
     * Seeks to a specific step index directly (scrub bar).
     * @param {number} index 
     */
    seek(index) {
        const targetIndex = Math.max(0, Math.min(this.steps.length - 1, index));
        if (targetIndex !== this.currentStepIndex) {
            this.currentStepIndex = targetIndex;
            this.notifyStep(false);
        }
    }

    /**
     * Resets timeline to initial state (step 0).
     */
    reset() {
        this.pause();
        if (this.steps.length > 0) {
            this.currentStepIndex = 0;
            this.notifyStep(false);
        }
    }

    /**
     * Dispatches notification to UI callbacks and plays sound tone.
     */
    notifyStep(triggerSound = true) {
        const step = this.getCurrentStep();
        if (!step) return;

        // Sound trigger (only if player has sound enabled and not muted)
        if (this.enableSound && triggerSound && window.soundSynth && step.indices && step.indices.length > 0) {
            const arr = step.arrayState;
            if (arr) {
                const min = Math.min(...arr);
                const max = Math.max(...arr);
                const firstIdx = step.indices[0];
                const val = arr[firstIdx] !== undefined ? arr[firstIdx] : 50;
                window.soundSynth.playTone(val, min, max, step.type);
            }
        }

        this.onStep(step, this.currentStepIndex, this.steps.length);
    }
}

window.AlgorithmPlayer = AlgorithmPlayer;
